### ISSUE TITLE
support mgmt (8089) without TLS

### ISSUE THREAD

**Issue by ryanfaircloth** [splunk/splunk-operator#185]
inside of a k8s network there are some valid reasons to disable ssl including performance when external network encryption such as weave is applied. The following options correctly use ansible to deconfigure ssl on this port however operator connections presume ssl.

  defaults: |-
    cert_prefix: http
    splunk:
      ssl:
        enable: false

Use cases TLS offload with external ingress and ISTIO mutal TLS auth (offloaded TLS)

**Comment by akondur** [comment]
Hi @rfaircloth-splunk , could you try using **defaults** or **defaultsUrl** [common spec parameter](https://github.com/splunk/splunk-operator/blob/master/docs/CustomResources.md#common-spec-parameters-for-splunk-enterprise-resources) to pass in the SSL options?

**Comment by rfaircloth-splunk** [comment]
the defaults portion works however operator is hard coded to connect by TLS so it breaks the operator if the instance is not TLS enabled

**Comment by jkoby** [comment]
This should work now, after a fix in the Docker image: https://github.com/splunk/docker-splunk/pull/488

**Comment by thooooooomas** [comment]
I don't think splunk-operator is supporting TLS off as the original poster intended..
The PR that adds support #194 seems to have never merged..

It is still confusing reading this issue if splunk-operator supports TLS off or not for mgmt port, is it or is it not supported?

**Comment by thooooooomas** [comment]
> This should work now, after a fix in the Docker image: [splunk/docker-splunk#488](https://github.com/splunk/docker-splunk/pull/488)

I believe this does not fix the issue that @ryanfaircloth mentioned in comment 3: that splunk-operator is hard coded to connect via https

**Comment by MaxRenaud** [comment]
@jkoby Can you please comment on @thooooooomas 's comment above? We are also interested in this and can create a new issue or reopen this one.
